In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype='float32')

In [3]:
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]],dtype='float32')

In [4]:
 # Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
print(inputs)
targets = torch.from_numpy(targets)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [5]:
 # Weights and biases
w = torch.randn(1,3,requires_grad =True)
print(w)
b = torch.randn(1,requires_grad=True)
print(b)

tensor([[-0.8613,  1.3306, -0.2317]], requires_grad=True)
tensor([1.2546], requires_grad=True)


In [6]:
# Define the model
def model(x):
  return torch.mm(x,w.t(),out=None) +b

In [7]:
# Generate predictions
# Compare with targets

preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)

Prediction : tensor([[ 17.5659],
        [ 25.1389],
        [ 91.1811],
        [-37.9549],
        [ 53.3414]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [8]:
# MSE loss
# Compute loss
def mse(P,T):
  diff = 0
  i=0
  sum=0
  n=len(T)
  for k in range(0,n):
    i+=1
    diff = T[k] - P[k]
    square = diff*diff
    sum+=square
  mean = sum/i
  return mean

output = mse(preds,targets)
print("Loss :",output)

Loss : tensor([2286.4175], grad_fn=<DivBackward0>)


In [9]:
# Compute gradients
print("Gradient :",output.backward())

Gradient : None


In [10]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.8613,  1.3306, -0.2317]], requires_grad=True)
tensor([[-7940.4502, -7425.5479, -5014.2793]])


In [11]:
# Gradients for bias
print(b)
print(b.grad)

tensor([1.2546], requires_grad=True)
tensor([-92.6910])


In [12]:
# Compute gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()
print(w)
print(b)

tensor([[-0.7819,  1.4048, -0.1816]], requires_grad=True)
tensor([1.2555], requires_grad=True)


In [13]:
# Generate predictions
# Calculate the loss
new_preds = model(inputs)
new_loss = mse(new_preds,targets)
print("New Loss :",new_loss)

New Loss : tensor([1108.7239], grad_fn=<DivBackward0>)


In [14]:
# Train for 100 epochs
for i in range(200):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [15]:
# Calculate loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor([38.1218], grad_fn=<DivBackward0>)


Pytorch_Built_Ins

In [16]:
 # Imports
import torch.nn as nn
print(inputs)
print(targets)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [17]:
def model1(x):
  return x @ w.t() +b

In [18]:
preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)

Prediction : tensor([[ 57.5244],
        [ 77.5732],
        [128.6580],
        [ 21.4525],
        [ 93.8914]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [19]:
loss = nn.MSELoss()
output = loss(preds,targets)
output.backward()
print("Loss :",output)

Loss : tensor(38.1218, grad_fn=<MseLossBackward0>)


In [20]:
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[-0.3092,  1.0994,  0.1203]], requires_grad=True)
tensor([[ -17.8606,   78.7115, -100.5846]])
tensor([1.2611], requires_grad=True)
tensor([-0.7602])


In [21]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [22]:
preds = model1(inputs)
loss = mse(preds,targets)
 
print(loss)

tensor([25.6746], grad_fn=<DivBackward0>)
