In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

In [2]:
lr=linear_model.LogisticRegression()
dt=DecisionTreeClassifier()
bn=BernoulliNB()

In [3]:
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)

In [4]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [5]:
df2=df.sample(frac=1)

In [6]:
df2.shape

(569, 31)

In [7]:
hold_on_data=df2.iloc[0:285,:]

In [8]:
hold_on_data.shape

(285, 31)

In [9]:
hold_on_data

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
436       12.870         19.54           82.67      509.2          0.09136   
141       16.110         18.05          105.10      813.0          0.09721   
348       11.470         16.03           73.02      402.7          0.09076   
25        17.140         16.40          116.00      912.7          0.11860   
61         8.598         20.98           54.66      221.8          0.12430   
..           ...           ...             ...        ...              ...   
342       11.060         14.96           71.49      373.9          0.10330   
560       14.050         27.15           91.38      600.4          0.09929   
192        9.720         18.22           60.73      288.1          0.06950   
253       17.300         17.08          113.00      928.2          0.10080   
133       15.710         13.93          102.00      761.7          0.09462   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
436           0.07883         0.01797             0.020900         0.1861   
141           0.11370         0.09447             0.059430         0.1861   
348           0.05886         0.02587             0.023220         0.1634   
25            0.22760         0.22290             0.140100         0.3040   
61            0.08963         0.03000             0.009259         0.1828   
..                ...             ...                  ...            ...   
342           0.09097         0.05397             0.033410         0.1776   
560           0.11260         0.04462             0.043040         0.1537   
192           0.02344         0.00000             0.000000         0.1653   
253           0.10410         0.12660             0.083530         0.1813   
133           0.09462         0.07135             0.059330         0.1816   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
436                 0.06347  ...          24.38            95.14       626.9   
141                 0.06248  ...          25.27           129.00      1233.0   
348                 0.06372  ...          20.79            79.67       475.8   
25                  0.07413  ...          21.40           152.40      1461.0   
61                  0.06757  ...          27.04            62.06       273.9   
..                      ...  ...            ...              ...         ...   
342                 0.06907  ...          19.90            79.76       440.0   
560                 0.06171  ...          33.17           100.20       706.7   
192                 0.06447  ...          20.83            62.25       303.8   
253                 0.05613  ...          25.09           130.90      1222.0   
133                 0.05723  ...          19.25           114.30       922.8   

     worst smoothness  worst compactness  worst concavity  \
436           0.12140            0.16520          0.07127   
141           0.13140            0.22360          0.28020   
348           0.15310            0.11200          0.09823   
25            0.15450            0.39490          0.38530   
61            0.16390            0.16980          0.09001   
..                ...                ...              ...   
342           0.14180            0.22100          0.22990   
560           0.12410            0.22640          0.13260   
192           0.07117            0.02729          0.00000   
253           0.14160            0.24050          0.33780   
133           0.12230            0.19490          0.17090   

     worst concave points  worst symmetry  worst fractal dimension  target  
436               0.06384          0.3313                  0.07735       1  
141               0.12160          0.2792                  0.08158       0  
348               0.06548          0.2851                  0.08763       1  
25                0.25500          0.4066                  0.10590       0  
61                0.02778          0.2972                  0.077

In [10]:
df1=df2.iloc[286:569,:]

In [11]:
y=df1.iloc[:,-1]

In [12]:
y

66     1
130    1
31     0
274    0
559    1
      ..
387    1
314    1
556    1
564    0
454    1
Name: target, Length: 283, dtype: int64

In [13]:
X=df1.iloc[:,:-1]

In [14]:
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
66         9.465         21.01           60.11      269.4          0.10440   
130       12.190         13.29           79.08      455.8          0.10660   
31        11.840         18.70           77.93      440.6          0.11090   
274       17.930         24.48          115.20      998.9          0.08855   
559       11.510         23.93           74.52      403.5          0.09261   
..           ...           ...             ...        ...              ...   
387       13.880         16.16           88.37      596.6          0.07026   
314        8.597         18.60           54.09      221.2          0.10740   
556       10.160         19.59           64.73      311.7          0.10030   
564       21.560         22.39          142.00     1479.0          0.11100   
454       12.620         17.15           80.62      492.9          0.08583   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
66            0.07773        0.021720             0.015040         0.1717   
130           0.09509        0.028550             0.028820         0.1880   
31            0.15160        0.121800             0.051820         0.2301   
274           0.07027        0.056990             0.047440         0.1538   
559           0.10210        0.111200             0.041050         0.1388   
..                ...             ...                  ...            ...   
387           0.04831        0.020450             0.008507         0.1607   
314           0.05847        0.000000             0.000000         0.2163   
556           0.07504        0.005025             0.011160         0.1791   
564           0.11590        0.243900             0.138900         0.1726   
454           0.05430        0.029660             0.022720         0.1799   

     mean fractal dimension  ...  worst radius  worst texture  \
66                  0.06899  ...        10.410          31.56   
130                 0.06471  ...        13.340          17.81   
31                  0.07799  ...        16.820          28.12   
274                 0.05510  ...        20.920          34.69   
559                 0.06570  ...        12.480          37.16   
..                      ...  ...           ...            ...   
387                 0.05474  ...        15.510          19.97   
314                 0.07359  ...         8.952          22.44   
556                 0.06331  ...        10.650          22.88   
564                 0.05623  ...        25.450          26.40   
454                 0.05826  ...        14.340          22.15   

     worst perimeter  worst area  worst smoothness  worst compactness  \
66             67.03       330.7           0.15480            0.16640   
130            91.38       545.2           0.14270            0.25850   
31            119.40       888.7           0.16370            0.57750   
274           135.10      1320.0           0.13150            0.18060   
559            82.28       474.2           0.12980            0.25170   
..               ...         ...               ...                ...   
387            99.66       745.3           0.08484            0.12330   
314            56.65       240.1           0.13470            0.07767   
556            67.88       347.3           0.12650            0.12000   
564           166.10      2027.0           0.14100            0.21130   
454            91.62       633.5           0.12250            0.15170   

     worst concavity  worst concave points  worst symmetry  \
66           0.09412               0.06517          0.2878   
130          0.09915               0.08187          0.3469   
31           0.69560               0.15460          0.4761   
274          0.20800               0.11360          0.2504   
559          0.36300               0.09653          0.2112   
..               ...                   ...             ...   
387          0.10910               0.04537         

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [16]:
X

array([[-1.31833249,  0.40611836, -1.30626529, ..., -0.75208204,
        -0.07908492,  0.54391164],
       [-0.56540064, -1.46284393, -0.54581081, ..., -0.49917975,
         0.89896813,  0.56182443],
       [-0.66210748, -0.15311776, -0.59191111, ...,  0.60223242,
         3.03711454,  3.41533189],
       ...,
       [-1.12630033,  0.06234551, -1.12106235, ..., -1.40099599,
        -1.09851076, -0.93031099],
       [ 2.02357971,  0.74020748,  1.97647678, ...,  1.61687033,
        -1.432803  , -0.7075953 ],
       [-0.44658937, -0.52836278, -0.4840765 , ..., -0.2471861 ,
         0.56964062, -0.5792203 ]])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [19]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
bn.fit(X_train,y_train)

BernoulliNB()

In [20]:
h_X=hold_on_data.iloc[:,:-1]
h_y=hold_on_data.iloc[:,-1]

In [21]:
h_X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
436       12.870         19.54           82.67      509.2          0.09136   
141       16.110         18.05          105.10      813.0          0.09721   
348       11.470         16.03           73.02      402.7          0.09076   
25        17.140         16.40          116.00      912.7          0.11860   
61         8.598         20.98           54.66      221.8          0.12430   
..           ...           ...             ...        ...              ...   
342       11.060         14.96           71.49      373.9          0.10330   
560       14.050         27.15           91.38      600.4          0.09929   
192        9.720         18.22           60.73      288.1          0.06950   
253       17.300         17.08          113.00      928.2          0.10080   
133       15.710         13.93          102.00      761.7          0.09462   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
436           0.07883         0.01797             0.020900         0.1861   
141           0.11370         0.09447             0.059430         0.1861   
348           0.05886         0.02587             0.023220         0.1634   
25            0.22760         0.22290             0.140100         0.3040   
61            0.08963         0.03000             0.009259         0.1828   
..                ...             ...                  ...            ...   
342           0.09097         0.05397             0.033410         0.1776   
560           0.11260         0.04462             0.043040         0.1537   
192           0.02344         0.00000             0.000000         0.1653   
253           0.10410         0.12660             0.083530         0.1813   
133           0.09462         0.07135             0.059330         0.1816   

     mean fractal dimension  ...  worst radius  worst texture  \
436                 0.06347  ...        14.450          24.38   
141                 0.06248  ...        19.920          25.27   
348                 0.06372  ...        12.510          20.79   
25                  0.07413  ...        22.250          21.40   
61                  0.06757  ...         9.565          27.04   
..                      ...  ...           ...            ...   
342                 0.06907  ...        11.920          19.90   
560                 0.06171  ...        15.300          33.17   
192                 0.06447  ...         9.968          20.83   
253                 0.05613  ...        19.850          25.09   
133                 0.05723  ...        17.500          19.25   

     worst perimeter  worst area  worst smoothness  worst compactness  \
436            95.14       626.9           0.12140            0.16520   
141           129.00      1233.0           0.13140            0.22360   
348            79.67       475.8           0.15310            0.11200   
25            152.40      1461.0           0.15450            0.39490   
61             62.06       273.9           0.16390            0.16980   
..               ...         ...               ...                ...   
342            79.76       440.0           0.14180            0.22100   
560           100.20       706.7           0.12410            0.22640   
192            62.25       303.8           0.07117            0.02729   
253           130.90      1222.0           0.14160            0.24050   
133           114.30       922.8           0.12230            0.19490   

     worst concavity  worst concave points  worst symmetry  \
436          0.07127               0.06384          0.3313   
141          0.28020               0.12160          0.2792   
348          0.09823               0.06548          0.2851   
25           0.38530               0.25500          0.4066   
61           0.09001               0.02778          0.2972   
..               ...                   ...             ...   
342          0.22990               0.10750         

In [22]:
h_X=sc.fit_transform(h_X)

In [23]:
x1=lr.predict(h_X)
x2=dt.predict(h_X)
x3=bn.predict(h_X)

In [24]:
x1

array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1])

In [25]:
x2

array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0])

In [26]:
x3

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [27]:
df3=pd.DataFrame(data=[x1,x2,x3])

In [28]:
df4=df3.T

In [29]:
df4

0  1  2
0    1  1  1
1    0  0  0
2    1  1  1
3    0  0  0
4    1  1  1
..  .. .. ..
280  1  1  1
281  1  1  1
282  1  0  1
283  0  0  0
284  1  0  0

[285 rows x 3 columns]

In [30]:
lr2=LogisticRegression()

In [31]:
df4_X=df4.iloc[:,:]
df4_Y=h_y

In [32]:
df4_X

0  1  2
0    1  1  1
1    0  0  0
2    1  1  1
3    0  0  0
4    1  1  1
..  .. .. ..
280  1  1  1
281  1  1  1
282  1  0  1
283  0  0  0
284  1  0  0

[285 rows x 3 columns]

In [33]:
df4_Y

436    1
141    0
348    1
25     0
61     1
      ..
342    1
560    1
192    1
253    0
133    1
Name: target, Length: 285, dtype: int64

In [34]:
lr2.fit(df4_X,df4_Y)

LogisticRegression()

In [35]:
X_test=sc.fit_transform(X_test)

In [36]:
X_test

array([[-1.8746333 ,  0.25560319, -1.78481682, ..., -0.66967351,
         0.62541724,  3.76041593],
       [ 0.59833967,  0.42743907,  0.62926269, ...,  1.35868727,
         1.11782329,  0.66535094],
       [-0.95331814, -0.53534728, -0.96693196, ..., -0.5425809 ,
         0.03486841, -0.39770103],
       ...,
       [-0.43121022,  0.26571118, -0.39288062, ..., -0.05966003,
        -0.65889956, -0.14698674],
       [ 1.49002961,  0.3945881 ,  1.48033955, ...,  1.87854104,
         1.11782329,  0.19431197],
       [-0.63066718,  0.05091633, -0.62905445, ..., -0.70908929,
        -0.45246128, -0.38659713]])

In [37]:
x4=lr.predict(X_test)
x5=dt.predict(X_test)
x6=bn.predict(X_test)

In [38]:
df5=pd.DataFrame(data=[x4,x5,x6])

In [40]:
df6=df5.T

In [41]:
df6

0  1  2
0   1  1  1
1   0  0  0
2   1  1  1
3   0  0  0
4   0  0  0
.. .. .. ..
89  0  0  0
90  1  1  1
91  1  1  1
92  0  0  0
93  1  1  1

[94 rows x 3 columns]

In [42]:
df6_X=df6.iloc[:,:]


In [43]:
final=lr2.predict(df6_X)

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, final)
precision = precision_score(y_test, final, average=None)
recall = recall_score(y_test, final, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         0.89090909]
recall: [0.86666667 1.        ]


In [45]:
from sklearn.ensemble import StackingClassifier

In [46]:
df_X=df.iloc[:,:-1]
df_y=df.iloc[:,-1]

In [47]:
df_X=sc.fit_transform(df_X)

In [48]:
df_X.shape

(569, 30)

In [49]:
df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df_X, df_y, test_size=0.33)

In [50]:
estimators=[('lr',LogisticRegression()),('dt',DecisionTreeClassifier()),('bn',BernoulliNB())]

In [51]:
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

In [52]:
clf.fit(df_X_train,df_y_train)

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('dt', DecisionTreeClassifier()),
                               ('bn', BernoulliNB())],
                   final_estimator=LogisticRegression())

In [53]:
final1=clf.predict(df_X_test)

In [54]:
accuracy_score(df_y_test, final1)

0.973404255319149

In [55]:
precision = precision_score(df_y_test, final1, average=None)
recall = recall_score(df_y_test, final1, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.97183099 0.97435897]
recall: [0.95833333 0.98275862]
